In [1]:
%pylab inline
import pandas as pd

Populating the interactive namespace from numpy and matplotlib


In [3]:
df = pd.read_csv('data-set.csv',
                 index_col=0,
                 parse_dates=True,
                 infer_datetime_format=True,
                 dayfirst=True)

In [4]:
df.columns
columns = df.columns.tolist()
rest_col = list(columns)

for col in columns:
    rest_col.remove(col)

    for other_col in rest_col:
        print df[col].corr(df[other_col]), col, other_col

0.261795264819 AvgBlockSize BitcoiDaysDestroyed
0.929837834423 AvgBlockSize BitcoinDaysDestroyedCumulative
0.245178892871 AvgBlockSize BitcoinDaysDestroyedMinMonth
0.25365665018 AvgBlockSize BitcoinDaysDestroyedMinWeek
0.188192071964 AvgBlockSize BitcoinDaysDestroyedMinYear
0.968017215404 AvgBlockSize BlockSize
0.222549427957 AvgBlockSize CostPerTransaction
-0.0229840829027 AvgBlockSize CostPerTransactionPercent
0.882508017358 AvgBlockSize Difficulty
0.217919292059 AvgBlockSize EstimatedTransactionVolume
0.725338088935 AvgBlockSize EstimatedTransactionVolumeUSD
-0.764016516396 AvgBlockSize EuroPriceInUSD
0.874946956144 AvgBlockSize HashRate
0.67033170822 AvgBlockSize MarketCap
0.608493611052 AvgBlockSize MarketPrice
0.472041920742 AvgBlockSize MedianConfirmationTime
0.546681339506 AvgBlockSize MinersRevenue
-0.542598509135 AvgBlockSize NetworkDeficit
0.978571558306 AvgBlockSize NumTransactions
0.969347363978 AvgBlockSize NumTransactionsExcluding10
0.974743185136 AvgBlockSize NumTransac

In [5]:
import numpy as np
columns = df.columns.tolist()
rest_col = list(columns)    
for col in columns:
    rest_col.remove(col)

    for other_col in rest_col:
        print np.correlate(df[col],df[other_col])[0], col, other_col

689.070061757 AvgBlockSize BitcoiDaysDestroyed
2445.25975952 AvgBlockSize BitcoinDaysDestroyedCumulative
645.335376725 AvgBlockSize BitcoinDaysDestroyedMinMonth
667.649151592 AvgBlockSize BitcoinDaysDestroyedMinWeek
495.342012371 AvgBlockSize BitcoinDaysDestroyedMinYear
2542.65217668 AvgBlockSize BlockSize
585.765606499 AvgBlockSize CostPerTransaction
-60.4966973345 AvgBlockSize CostPerTransactionPercent
2311.4603075 AvgBlockSize Difficulty
573.547706224 AvgBlockSize EstimatedTransactionVolume
1906.98255676 AvgBlockSize EstimatedTransactionVolumeUSD
-2010.03423814 AvgBlockSize EuroPriceInUSD
2294.39077813 AvgBlockSize HashRate
1763.39171887 AvgBlockSize MarketCap
1601.06408668 AvgBlockSize MarketPrice
1242.25555914 AvgBlockSize MedianConfirmationTime
1438.6734504 AvgBlockSize MinersRevenue
-1427.94615819 AvgBlockSize NetworkDeficit
2568.54625314 AvgBlockSize NumTransactions
2543.56627454 AvgBlockSize NumTransactionsExcluding10
2558.05591007 AvgBlockSize NumTransactionsExcluding100
2561

In [5]:
from sklearn import linear_model

Xs = df[[u'AvgBlockSize', u'BitcoiDaysDestroyed', u'BitcoinDaysDestroyedCumulative',
         u'BitcoinDaysDestroyedMinMonth', u'BitcoinDaysDestroyedMinWeek',
         u'BitcoinDaysDestroyedMinYear', u'BlockSize', u'CostPerTransaction',
         u'CostPerTransactionPercent', u'Difficulty', u'EstimatedTransactionVolume',
         u'EstimatedTransactionVolumeUSD', u'EuroPriceInUSD', u'HashRate', u'MarketCap',
         u'MarketPrice', u'MedianConfirmationTime', u'MinersRevenue', u'NetworkDeficit',
         u'NumTransactions', u'NumTransactionsExcluding10', u'NumTransactionsExcluding100',
         u'NumTransactionsExcluding1000', u'NumTransactionsExcluding10000',
         u'NumTransactionsExcludingPopular', u'NumTransactionsPerBlock',
         u'NumTransactionsTotal', u'NumUniqueAdresses', u'OutputVolume', u'Open',
         u'High', u'Low', u'Close', u'Volume', u'Adj-Close', u'TotalBitcoins',
         u'TradeVolume', u'TransactionFees', u'TransactionFeesUSD',
         u'TxTradeRatio', u'WikipediaTrend']].values

ys = df[[u'NextDayPrice']].values

clf = linear_model.Lasso(alpha=0.001, max_iter=4000)
clf.fit(Xs, ys)
print clf.coef_

[  0.00000000e+00   0.00000000e+00   3.79137460e-03   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   7.67677914e-03
   0.00000000e+00   0.00000000e+00  -0.00000000e+00   6.60854218e-03
   0.00000000e+00   0.00000000e+00   1.07535501e-03   9.81735879e-01
   0.00000000e+00   0.00000000e+00  -0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   6.38922354e-05   0.00000000e+00   0.00000000e+00
  -0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00  -0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   8.55818415e-05]


In [7]:
from sklearn import decomposition
pca = decomposition.PCA()
pca.fit(Xs)

PCA(copy=True, n_components=None, whiten=False)

In [8]:
print(pca.explained_variance_)

[  2.34987403e+01   4.30478022e+00   3.23803319e+00   2.01835163e+00
   1.24201965e+00   1.00934440e+00   9.93973651e-01   8.45684122e-01
   7.67649439e-01   6.90501487e-01   5.31804284e-01   4.04114316e-01
   2.71919487e-01   2.49584536e-01   1.64688584e-01   1.51873620e-01
   1.35322772e-01   9.36165449e-02   7.23479475e-02   5.10704881e-02
   3.79859215e-02   3.18580222e-02   2.86276691e-02   2.32063519e-02
   1.37899309e-02   1.06127064e-02   6.69438132e-03   5.22585082e-03
   4.61800254e-03   3.06245663e-03   2.81392990e-03   1.90501312e-03
   9.93826947e-04   7.51456737e-04   2.35242179e-04   1.85520738e-04
   9.23042425e-05   5.64210717e-05   3.81643103e-05   3.70910223e-09
   2.01924234e-31]


In [9]:
X_new = pca.transform(Xs)
X_new

array([[ -5.73146653e+00,   1.34001076e+00,   7.05018170e-01, ...,
          5.56318557e-05,  -3.95768819e-06,  -1.01904665e-16],
       [ -5.46312085e+00,   9.42873867e-01,   4.08245644e-01, ...,
          8.93444106e-04,  -1.22604999e-06,  -1.08341446e-18],
       [ -5.23614327e+00,   8.27824540e-01,   2.86460452e-01, ...,
          2.17975684e-03,  -2.50763229e-06,  -1.84708821e-16],
       ..., 
       [  1.36575258e+01,   3.36592049e+00,   2.82710226e+00, ...,
         -2.02741850e-02,  -1.12563618e-04,  -1.34444907e-17],
       [  1.92244063e+01,   3.57812422e+00,   2.83301354e+00, ...,
          3.34013950e-02,  -4.09694843e-05,   1.98690751e-16],
       [  1.40575523e+01,   5.02974134e+00,   1.69769865e+00, ...,
         -1.74665381e-02,  -1.01664661e-04,  -8.66648948e-17]])

In [11]:
V = pca.transform(np.eye(Xs.shape[1]))
X_new_bis = Xs.dot(V)

In [12]:
X_new_bis

array([[ -5.88691489e+00,   1.28472665e+00,   6.87182463e-01, ...,
          2.53975182e-04,  -3.27966439e-06,  -2.41945509e-16],
       [ -5.62027281e+00,   8.86983891e-01,   3.90214471e-01, ...,
          1.09396112e-03,  -5.40595567e-07,  -3.35348076e-16],
       [ -5.39181225e+00,   7.72461972e-01,   2.68599431e-01, ...,
          2.37838167e-03,  -1.82864619e-06,  -2.78213273e-16],
       ..., 
       [  1.40396862e+01,   3.50183311e+00,   2.87095027e+00, ...,
         -2.07618000e-02,  -1.14230498e-04,   2.35009672e-16],
       [  1.98149904e+01,   3.78816128e+00,   2.90077550e+00, ...,
          3.26478429e-02,  -4.35454531e-05,   4.48877989e-16],
       [  1.44451526e+01,   5.16758863e+00,   1.74217082e+00, ...,
         -1.79610942e-02,  -1.03355269e-04,   1.63867227e-16]])

In [24]:
np.linalg.norm(X_new_bis - X_new, "fro")
df.describe()

       AvgBlockSize  BitcoiDaysDestroyed  BitcoinDaysDestroyedCumulative  \
count   2639.000000          2639.000000                     2639.000000   
mean      -0.001405            -0.000070                       -0.000821   
std        0.997579             1.000183                        0.999299   
min       -0.783896            -0.527324                       -1.003874   
25%       -0.779767            -0.464251                       -0.954433   
50%       -0.348572            -0.215759                       -0.391428   
75%        0.384442             0.067366                        0.941448   
max        3.778475            21.874844                        2.165781   

       BitcoinDaysDestroyedMinMonth  BitcoinDaysDestroyedMinWeek  \
count                   2639.000000                  2639.000000   
mean                      -0.000059                    -0.000064   
std                        1.000185                     1.000184   
min                       -0.472672        

In [26]:
df2 = df - df.mean()

In [28]:
df.mean()

AvgBlockSize                      -0.001405
BitcoiDaysDestroyed               -0.000070
BitcoinDaysDestroyedCumulative    -0.000821
BitcoinDaysDestroyedMinMonth      -0.000059
BitcoinDaysDestroyedMinWeek       -0.000064
BitcoinDaysDestroyedMinYear       -0.000030
BlockSize                         -0.001252
CostPerTransaction                 0.000107
CostPerTransactionPercent          0.000011
Difficulty                        -0.001926
EstimatedTransactionVolume        -0.000233
EstimatedTransactionVolumeUSD     -0.000932
EuroPriceInUSD                     0.000596
HashRate                          -0.001678
MarketCap                         -0.000655
MarketPrice                       -0.000515
MedianConfirmationTime            -0.000360
MinersRevenue                     -0.000366
NetworkDeficit                     0.000353
NumTransactions                   -0.001451
NumTransactionsExcluding10        -0.001527
NumTransactionsExcluding100       -0.001495
NumTransactionsExcluding1000    

In [30]:
df2.mean()

AvgBlockSize                      -2.397981e-16
BitcoiDaysDestroyed                3.626210e-16
BitcoinDaysDestroyedCumulative    -3.533866e-17
BitcoinDaysDestroyedMinMonth       8.599285e-16
BitcoinDaysDestroyedMinWeek       -5.864746e-16
BitcoinDaysDestroyedMinYear        2.282015e-15
BlockSize                         -2.441733e-16
CostPerTransaction                 2.274958e-15
CostPerTransactionPercent         -4.281395e-17
Difficulty                         3.034413e-15
EstimatedTransactionVolume        -5.175011e-16
EstimatedTransactionVolumeUSD     -6.776610e-16
EuroPriceInUSD                    -7.740850e-17
HashRate                          -2.480438e-16
MarketCap                          3.198149e-16
MarketPrice                        1.540597e-16
MedianConfirmationTime            -9.157762e-15
MinersRevenue                     -4.132436e-15
NetworkDeficit                    -2.809424e-15
NumTransactions                    5.273875e-16
NumTransactionsExcluding10        -6.976

In [32]:
Xs = df2[[u'AvgBlockSize', u'BitcoiDaysDestroyed', u'BitcoinDaysDestroyedCumulative',
         u'BitcoinDaysDestroyedMinMonth', u'BitcoinDaysDestroyedMinWeek',
         u'BitcoinDaysDestroyedMinYear', u'BlockSize', u'CostPerTransaction',
         u'CostPerTransactionPercent', u'Difficulty', u'EstimatedTransactionVolume',
         u'EstimatedTransactionVolumeUSD', u'EuroPriceInUSD', u'HashRate', u'MarketCap',
         u'MarketPrice', u'MedianConfirmationTime', u'MinersRevenue', u'NetworkDeficit',
         u'NumTransactions', u'NumTransactionsExcluding10', u'NumTransactionsExcluding100',
         u'NumTransactionsExcluding1000', u'NumTransactionsExcluding10000',
         u'NumTransactionsExcludingPopular', u'NumTransactionsPerBlock',
         u'NumTransactionsTotal', u'NumUniqueAdresses', u'OutputVolume', u'Open',
         u'High', u'Low', u'Close', u'Volume', u'Adj-Close', u'TotalBitcoins',
         u'TradeVolume', u'TransactionFees', u'TransactionFeesUSD',
         u'TxTradeRatio', u'WikipediaTrend']].values

ys = df2[[u'NextDayPrice']].values

pca = decomposition.PCA()
pca.fit(Xs)

PCA(copy=True, n_components=None, whiten=False)

In [34]:
V = pca.transform(np.eye(Xs.shape[1]))
X_new_bis = Xs.dot(V)
X_new_bis

array([[ -5.73146653e+00,   1.34001076e+00,   7.05018170e-01, ...,
          5.56318558e-05,  -3.95768825e-06,   1.45859697e-16],
       [ -5.46312085e+00,   9.42873867e-01,   4.08245644e-01, ...,
          8.93444106e-04,  -1.22605005e-06,   1.75913886e-16],
       [ -5.23614327e+00,   8.27824540e-01,   2.86460452e-01, ...,
          2.17975684e-03,  -2.50763235e-06,   1.62052711e-16],
       ..., 
       [  1.36575258e+01,   3.36592049e+00,   2.82710226e+00, ...,
         -2.02741850e-02,  -1.12563618e-04,   2.64001819e-17],
       [  1.92244063e+01,   3.57812422e+00,   2.83301354e+00, ...,
          3.34013950e-02,  -4.09694841e-05,  -1.82689043e-16],
       [  1.40575523e+01,   5.02974134e+00,   1.69769865e+00, ...,
         -1.74665381e-02,  -1.01664661e-04,  -2.75909706e-17]])

In [36]:
X_new = pca.transform(Xs)
X_new

array([[ -5.73146653e+00,   1.34001076e+00,   7.05018170e-01, ...,
          5.56318557e-05,  -3.95768819e-06,   1.72798225e-16],
       [ -5.46312085e+00,   9.42873867e-01,   4.08245644e-01, ...,
          8.93444106e-04,  -1.22604999e-06,  -1.91921916e-17],
       [ -5.23614327e+00,   8.27824540e-01,   2.86460452e-01, ...,
          2.17975684e-03,  -2.50763229e-06,  -3.30533660e-17],
       ..., 
       [  1.36575258e+01,   3.36592049e+00,   2.82710226e+00, ...,
         -2.02741850e-02,  -1.12563618e-04,   5.33387097e-17],
       [  1.92244063e+01,   3.57812422e+00,   2.83301354e+00, ...,
          3.34013950e-02,  -4.09694843e-05,  -1.55750515e-16],
       [  1.40575523e+01,   5.02974134e+00,   1.69769865e+00, ...,
         -1.74665381e-02,  -1.01664661e-04,  -6.52442876e-19]])

In [38]:
np.linalg.norm(X_new - X_new_bis, "fro")

1.4867517448657469e-11

In [39]:
V

array([[  1.94119088e-01,   1.19129530e-01,   4.94138522e-02, ...,
         -8.48835802e-03,  -5.44045656e-07,   1.15333311e-30],
       [  7.75730964e-02,  -3.02244890e-01,   3.68091283e-01, ...,
         -1.01770196e-01,  -9.78949544e-05,   2.78933946e-16],
       [  2.01017815e-01,   3.03530201e-02,  -4.15137028e-02, ...,
          1.07844281e-01,  -3.01288663e-05,   1.22141786e-16],
       ..., 
       [  1.54048025e-01,  -4.25126629e-02,  -2.39946191e-02, ...,
          1.60148085e-03,  -9.10050362e-03,  -1.47239705e-17],
       [  1.33212882e-01,   1.12876077e-01,   9.78841623e-02, ...,
          1.60200194e-03,   1.09325138e-06,   1.30316783e-18],
       [  5.14632449e-02,  -1.61267704e-01,  -1.84275640e-02, ...,
         -4.28089007e-04,  -1.18501437e-06,  -2.00136424e-18]])

In [40]:
print(pca.explained_variance_)

[  2.34987403e+01   4.30478022e+00   3.23803319e+00   2.01835163e+00
   1.24201965e+00   1.00934440e+00   9.93973651e-01   8.45684122e-01
   7.67649439e-01   6.90501487e-01   5.31804284e-01   4.04114316e-01
   2.71919487e-01   2.49584536e-01   1.64688584e-01   1.51873620e-01
   1.35322772e-01   9.36165449e-02   7.23479475e-02   5.10704881e-02
   3.79859215e-02   3.18580222e-02   2.86276691e-02   2.32063519e-02
   1.37899309e-02   1.06127064e-02   6.69438132e-03   5.22585082e-03
   4.61800254e-03   3.06245663e-03   2.81392990e-03   1.90501312e-03
   9.93826947e-04   7.51456737e-04   2.35242179e-04   1.85520738e-04
   9.23042425e-05   5.64210717e-05   3.81643103e-05   3.70910223e-09
   2.01924234e-31]
